dnf install epel-release
dnf install 'dnf-command(config-manager)'
dnf config-manager --set-enabled PowerTools
yum install R
yum install make gcc gcc-c++ libcurl-devel libxml2-devel openssl-devel 
yum install texlive-*
yum install git
